#! /bin/sh
#
# Move dotfiles into place
#

SRC=$HOME/src/dotfiles

logline() {
   echo "*** $1"
}

#prune() {
#    # rm old dotfile symlinks directly inside target directory
#    logline 'Pruning old symlinks...'
#    find -L "$1" -maxdepth 1 -type l -name '.*' -exec /bin/rm -i -- {} +
#}

link_dotfiles() {
    find "$1" -maxdepth 1 -name '.?*' -exec /bin/ln -f -s -v "$SRC/{}" $HOME \;
}

# Link dotfiles
logline "Creating common symlinks..."
link_dotfiles common

if [ -n "$1" ]; then
	logline "Creating symlinks for $1..."
	link_dotfiles $1
fi

#prune "$HOME"
