#! /bin/sh

DATESTAMP=`date +%Y.%m.%d`
SOURCE="/home/andrew/"
TARGET_DIR="backup/current"
BACKUP_DIR="backup/previous/${DATESTAMP}"
TARGET="andrew@192.168.1.8:${TARGET_DIR}"
DELETED="/volume1/homes/andrew/${BACKUP_DIR}"

#eval rsync --backup --backup-dir=`date +%Y.%m.%d` -avz --no-links --exclude=.cache --exclude='*.pyc' --exclude='.local' --exclude='*.core' --exclude='.dbus' --exclude='.racket' "${SOURCE}" "${TARGET}"
# exec rsync --backup --backup-dir=`date +%Y.%m.%d` --progress -avh --exclude-from="$HOME/src/dotfiles/home/backup.exclude" --exclude='.racket' "${SOURCE}" "${TARGET}" "$@"

exec rsync --backup --backup-dir="${DELETED}" --progress -avh --exclude-from="$HOME/src/dotfiles/home/backup.exclude" "${SOURCE}" "${TARGET}" "$@"
